name: Upload Website

on:
  push:
    branches:
    - main
env:
  SOURCE_DIR: 'server.js'

jobs:
  testJob:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: test_loc
      run: |
        content=`cat ./Location/comfort.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=testJson::$content"
     - run: |
          echo "${{fromJson(steps.test_loc.outputs.testJson).test}}"