


    

name: Upload Website

on:
  push:
    branches:
    - main
env:
  SOURCE_DIR: 'server.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test_loc
        run: |
          content=`cat ./Location/jsonconfig.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=testJson::$content"
         run: |
            echo "${{fromJson(steps.test_loc.outputs.testJson).newlocation}}"